main:
  separator: '-'
  description: 2232 South Highway 94, Defiance, Missouri 63341, Home for Sale
  endorse: false
  externalLinks:
    cue: true
    tab: true
#  build:
#    transpiler: dartsass

navigation:
  logo: 
#  color: body
  fixed: true
#  horizontal: false
  offset: 3em
  search: false
#  searchModal: false
  breadcrumb: false
#  toc: true
  sidebar: false
#  size: lg

home:
  fullCover: true
  centerHeadline: true
  feature:
    orientation: stacked
    color: ''
    width: 7
    align: start

sharing:
  enabled: false

links:
    google-maps: https://www.google.com/maps/search/?api=1&query=38.651210994217436%2C-90.76545807927727
    ag-district: https://ecode360.com/27756246
    katy: https://mostateparks.com/park/katy-trail-state-park
    defiance-ridge: https://www.defianceridgevineyards.com
    good-news: https://www.goodnewsbrewing.com
    klondike-park: https://www.sccmo.org/690/Klondike-Park
    augusta: https://www.townofaugustamo.org
    udc: https://ecode360.com/27756317
    huber: https://www.huberwood.com/advantech/subflooring
    toto: https://www.totousa.com/drake-two-piece-toilet-16-gpf-elongated-bowl
    doug-fir: https://www.loewen.com/product-features/wood-species/
    clad: https://www.loewen.com/product-features/aluminum-cladding/
    terrace: https://www.loewen.com/terrace-door
    emtek: https://www.emtek.com/all-products/door-hardware/knobs-lever-and-rosettes/leversets/luzern-leverset/
    allegheny: https://solidhardwooddoors.com
    rachio: https://rachio.com/products/rachio-3
    ridge-guard: https://www.animaltrapsandsupplies.com/products/ridgeguard-ridge-vent-animal-exclusion.html
    hardie-soffit: https://www.jameshardie.com/products/hardiesoffit-panels
    hardie-lap: https://www.jameshardie.com/products/hardieplank-lap-siding
    hardie-trim: https://www.jameshardie.com/products/hardietrim-boards
    hardie-shingle: https://www.jameshardie.com/products/hardieshingle-siding