main:
  separator: '-'
  description: 2232 South Highway 94, Defiance, Missouri 63341, Home for Sale
  endorse: false
  externalLinks:
    cue: true
    tab: true
#  build:
#    transpiler: dartsass

navigation:
  logo: 
#  color: body
  fixed: true
#  horizontal: false
  offset: 3em
  search: false
#  searchModal: false
  breadcrumb: false
#  toc: true
  sidebar: false
#  size: lg

home:
  fullCover: true
  centerHeadline: true
  feature:
    orientation: stacked
    color: ''
    width: 7
    align: start

sharing:
  enabled: false

links:
    google-maps: https://www.google.com/maps/search/?api=1&query=38.651210994217436%2C-90.76545807927727
    ag-district: https://ecode360.com/27756246
    katy: https://mostateparks.com/park/katy-trail-state-park
    defiance-ridge: https://www.defianceridgevineyards.com
    good-news: https://www.goodnewsbrewing.com
    augusta: https://www.townofaugustamo.org
    udc: https://ecode360.com/27756317
    huber: https://www.huberwood.com/advantech/subflooring
    toto: https://www.totousa.com/drake-two-piece-toilet-16-gpf-elongated-bowl
    doug-fir: https://www.loewen.com/product-features/wood-species/
    clad: https://www.loewen.com/product-features/aluminum-cladding/
    terrace: https://www.loewen.com/terrace-door
    emtek: https://www.emtek.com/all-products/door-hardware/knobs-lever-and-rosettes/leversets/luzern-leverset/
    allegheny: https://solidhardwooddoors.com
    rachio: https://rachio.com/products/rachio-3
    ridge-guard: https://www.animaltrapsandsupplies.com/products/ridgeguard-ridge-vent-animal-exclusion.html
    hardie-soffit: https://www.jameshardie.com/products/hardiesoffit-panels
    hardie-lap: https://www.jameshardie.com/products/hardieplank-lap-siding
    hardie-trim: https://www.jameshardie.com/products/hardietrim-boards
    hardie-shingle: https://www.jameshardie.com/products/hardieshingle-siding
    vssl: https://www.vssl.com/products/vssl-a-1x-home
    theater-seats: https://us.valenciatheaterseating.com/products/valencia-tuscany
    unifi-u6-lr: https://store.ui.com/us/en/pro/category/all-wifi/products/u6-lr
    unifi-u6-pro: https://store.ui.com/us/en/products/u6-pro
    unifi-u6-mesh: https://store.ui.com/us/en/products/u6-mesh
    unifi-dm-pro: https://store.ui.com/us/en/products/udm-pro
    eyezon: https://www.eyezon.com/evl4.php
    hik-nvr: https://www.hikvision.com/au-en/products/IP-Products/Network-Video-Recorders/Pro-Series/ds-7616ni-i2-16p/
    weatherflow: https://tempest.earth/tempest-home-weather-system/
    weather-underground: https://www.wunderground.com/dashboard/pws/KMODEFIA18?cm_ven=localwx_pwsdash
    nws-washington: https://water.weather.gov/ahps2/hydrograph.php?gage=whgm7&wfo=lsx
    lewis-and-clark: https://www.alltrails.com/trail/us/missouri/lewis-and-clark-trail-and-lewis-trail-loop
    lost-valley-trail: https://www.alltrails.com/trail/us/missouri/lost-valley-trail-loop
    hubitat: https://hubitat.com/
    samsung-ru8000: https://www.samsung.com/us/televisions-home-theater/tvs/premium-uhd-tvs/65--class-ru8000-premium-smart-4k-uhd-tv--2019--un65ru8000fxza/
    clopay: https://www.clopaydoor.com/coachman
    matson: https://www.sccmo.org/713/Matson-Hill-Park
    matson-map: https://www.sccmo.org/DocumentCenter/View/8668/Matson-Hill-Park-Trail-Map-PDF
    klondike-park: https://www.sccmo.org/690/Klondike-Park
    klondike-park-map: https://www.sccmo.org/DocumentCenter/View/19286/Klondike-Park-Map?bidId=
    the-district: https://www.thedistrictstl.com/
