main:
  separator: '-'
  description: 2232 South Highway 94, Defiance, Missouri 63341, Home for Sale
  endorse: false
  footerBelowFold: true
  canonifyAssetsURLs: true
  externalLinks:
    cue: true
    tab: true
  build:
    transpiler: dartsass

navigation:
  logo: 
  color: body
  fixed: true
  horizontal: false
  offset: 3em
  search: false
  searchModal: false
  breadcrumb: false
  toc: true
  sidebar: false

sharing:
  enabled: true
  sort: weight
  reverse: false
  webshare: true
  providers:
  - name: Facebook
    url: 'https://www.facebook.com/sharer.php?u={url}'
    icon: fab facebook
    weight: 10
  - name: email
    url: '{url}'
    icon: fas link
    weight: 20
    clipboard: true