main:
  separator: '-'
  description: 2232 South Highway 94, Defiance, Missouri 63341, Home for Sale
  endorse: false
  enableDarkMode: true
  modes:
    - light
    - dark
  canonifyAssetsURLs: false
  footerBelowFold: false
  loading: lazy
  externalLinks:
    cue: true
    tab: true
  build:
    transpiler: dartsass

navigation:
  logo: 
  color: body
  fixed: true
  horizontal: false
  offset: 3em
  search: false
  searchModal: false
  breadcrumb: false
  toc: true
  sidebar: false
  size: lg

home:
  fullCover: true
  centerHeadline: true
  style: gradient-featured
  feature:
    orientation: stacked
    color: ''
    width: 7
    align: start

sharing:
  enabled: false

modules:
  core:
    - bootstrap
    - flexsearch
    - fontawesome
  optional:
    - leaflet
    - katex
    - lottie
  excludeSCSS:
    - bootstrap
  disableTemplate:
    - katex
  katex:
    state: defer
  fontawesome:
    inline: true
    debug: true
    skipMissing: false
