main:
  - identifier: home
    name: Home
    url: /
    weight: 10

  - identifier: the-property
    name: The Property
    url: /01-the-property/
    weight: 20
    
  - identifier: the-home
    name: The Home
    url: /02-the-home/
    weight: 30

  - identifier: main-level
    name: Main Level
    url: /03-main-level/
    weight: 40

  - identifier: lower-level
    name: Lower Level
    url: /04-lower-level/
    weight: 50

  - identifier: garage
    name: Garage
    url: /05-garage/
    weight: 60

  - identifier: home-systems
    name: Home Systems
    url: /06-home-systems/
    weight: 70
        
  - identifier: recreation
    name: Recreation
    url: /07-recreation/
    weight: 80

  - identifier: contact
    name: Contact
    url: /contact/contact/
    weight: 90
