main:
  - identifier: home
    name: Home
    url: /
    weight: 10

  - identifier: property
    name: The Property
    url: /property-info/
    weight: 20
    
  - identifier: overview
    name: The Home
    url: /overview/
    weight: 30

  - identifier: main-level
    name: Main Level
    url: /main-level/
    weight: 40

  - identifier: lower-level
    name: Lower Level
    url: /lower-level/
    weight: 50

  - identifier: garage
    name: Garage
    url: /garage/
    weight: 60

  - identifier: home-systems
    name: Home Systems
    url: /home-systems/
    weight: 70
        
  - identifier: recreation
    name: Recreation
    url: /recreation/
    weight: 80

  - identifier: area
    name: Defiance Area
    url: /area/
    weight: 90

  - identifier: contact
    name: Contact
    url: /contact/
    weight: 100
